### ISSUE TITLE
Create buffer gate input

### ISSUE THREAD

**Issue by ByronPhung** [ByronPhung/combinational-logic-simulator#2]
Requested by @joeasds on 04/01

As far as I'm aware, a buffer gate simply passes input to output unchanged, mainly used for propagation delay. Functionality-wise, this can be accomplished by just linking the input that was supposed to go into the buffer gate into the buffer gate's output, but some users may want to just verify that the buffer gate is receiving the right input as expected.

**Comment by joeasds** [comment]
And, if there are some buffers in the circuit, manual modification may be troublesome.

**Comment by ByronPhung** [comment]
Merged to master on 04/02 as v1.1.2.
